module.exports = {
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1a153f",
        "tertiary": "#5b5784",
        "surface-bright": "#fcf8ff",
        "primary-fixed": "#e3dfff",
        "on-secondary-fixed-variant": "#493f72",
        "secondary-fixed": "#e6deff",
        "on-primary-fixed-variant": "#434270",
        "on-primary-fixed": "#171542",
        "inverse-primary": "#c4c1f8",
        "on-tertiary-fixed-variant": "#46426d",
        "secondary-container": "#cdc1fe",
        "background": "#fcf8ff",
        "outline-variant": "#E0D9FC",
        "surface-variant": "#e3dfff",
        "on-surface-variant": "#47464f",
        "surface-dim": "#d9d6ff",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-background": "#171542",
        "inverse-on-surface": "#f2efff",
        "outline": "#78767f",
        "error": "#ba1a1a",
        "on-surface": "#171542",
        "surface-container-low": "#f6f2ff",
        "primary-fixed-dim": "#c4c1f8",
        "secondary": "#C8BCF8",
        "primary": {
          DEFAULT: "#7C7AAC",
          dark: "#4A4880",
          darker: "#2A2650"
        },
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#e4dfff",
        "tertiary-fixed-dim": "#c7c1f5",
        "surface": "#F8F6FF",
        "on-error": "#ffffff",
        "surface-tint": "#5b5989",
        "on-secondary-container": "#574d81",
        "surface-container-high": "#e9e5ff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#cbbffb",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2d2b58",
        "surface-container-highest": "#e3dfff",
        "surface-container": "#efebff",
        "on-secondary-fixed": "#1d1244",
        "tertiary-container": "#746f9e",
        "primary-container": "#7170a1",
        "border": "#E0D9FC"
      },
      borderRadius: {
        "DEFAULT": "4px",
        "lg": "8px",
        "xl": "12px",
        "rounded-card": "24px",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "xxl": "32px",
        "xl": "24px",
        "lg": "20px",
        "xs": "4px",
        "sm": "8px",
        "unit": "4px",
        "gutter": "16px",
        "card-padding": "20px",
        "space-stack-gap": "16px",
        "card-internal-padding": "20px"
      },
      fontFamily: {
        "label-caps": ["DM Sans"],
        "h1": ["Plus Jakarta Sans"],
        "h3": ["Plus Jakarta Sans"],
        "body": ["DM Sans"],
        "h2": ["Plus Jakarta Sans"],
        "badge": ["DM Sans"]
      },
      fontSize: {
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "500" }],
        "h1": ["22px", { "lineHeight": "32px", "fontWeight": "600" }],
        "h3": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body": ["14px", { "lineHeight": "22.4px", "fontWeight": "400" }],
        "h2": ["17px", { "lineHeight": "24px", "fontWeight": "500" }],
        "badge": ["11px", { "lineHeight": "1", "fontWeight": "500" }],
        "h1-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "700" }]
      }
    },
  },
};