// ============================================================
// KAYOD HRIS — Constants and Lookups
// ============================================================

// Philippine Cities
export const PHILIPPINE_CITIES = [
  "Manila",
  "Quezon City",
  "Cebu City",
  "Davao City",
  "Cagayan de Oro",
  "Zamboanga City",
  "Santa Rosa",
  "Makati",
  "Pasig",
  "Taguig",
  "Caloocan",
  "Las Piñas",
  "Parañaque",
  "Muntinlupa",
  "Navotas",
  "Malabon",
  "San Juan",
  "Marikina",
  "Valenzuela",
  "Cavite",
  "Laguna",
  "Batangas",
  "Antipolo",
  "Tanay",
  "Rodriguez",
  "Cainta",
  "Bauan",
  "Lipa",
  "Nasugbu",
  "Rosario",
  "Malolos",
  "San Fernando",
  "Pampanga",
  "Angeles City",
  "Cabanatuan",
  "Nueva Ecija",
  "San Jose del Monte",
  "Bulacan",
  "Baguio City",
  "Cordova",
  "Mandaue City",
  "Lapu-Lapu City",
  "Carcar",
  "Talisay",
  "Minglanilla",
  "Consolacion",
  "Moalboal",
  "Oslob",
  "Samboan",
  "Catmon",
  "Dumaguete City",
  "Sibulan",
  "Bais City",
  "Bayawan City",
  "Iloilo City",
  "Roxas City",
  "Kalibo",
  "Bacolod City",
  "Victorias",
  "Silay",
  "Kabankalan",
  "Himamaylan",
  "San Carlos",
  "La Carlota",
  "Negros Oriental",
  "General Santos City",
  "Koronadal City",
  "Tacurong City",
  "Cotabato City",
  "Marbel",
  "Sultan Kudarat",
  "Calinog",
  "Janiuay",
  "Iloilo",
  "Legaspi City",
  "Naga City (Camarines)",
  "Sorsogon City",
  "Libmanan",
  "Bulan",
  "Camarines Sur",
  "Albay",
  "Camarines Norte",
  "Marinduque",
  "Romblon",
  "Capiz",
  "Antique",
  "Palawan",
  "Puerto Princesa",
  "El Nido",
  "Coron",
  "Sipalay",
  "Batangas City",
  "Tanauan",
  "Lipa",
  "Batangueño",
  "Tagaytay",
  "Mabini",
  "Calatagan",
  "Lemery",
  "San Pascual",
  "Mataasnakahon",
  "Taal",
  "Ilagan",
  "Tuguegarao City",
  "Isabela",
  "Nueva Vizcaya",
  "Quirino",
  "Aurora",
  "Baler",
  "Dipolog",
  "Dapitan City",
  "Zamboanga del Norte",
  "Zamboanga del Sur",
  "Zamboanga Sibugay",
  "Misamis Oriental",
  "Misamis Occidental",
  "Bukidnon",
  "Lanao del Norte",
  "Lanao del Sur",
  "Iligan City",
  "Marawi City",
  "Gingoog City",
  "Basilan",
  "Sulu",
  "Tawi-Tawi",
  "Maguindanao",
  "Sultan Fundamental Naseeb",
  "Cotabato",
  "Sarangani",
  "South Cotabato",
  "Surigao City",
  "Surigao del Norte",
  "Surigao del Sur",
  "Butuan City",
  "Aqusan del Norte",
  "Agusan del Sur",
  "Dinagat Islands",
  "Lianga",
  "Remote"
];

// Job Industries  
export const JOB_INDUSTRIES = [
  { id: "it", label: "IT/Technology", fields: ["Software Engineer", "WebDeveloper", "Backend Developer", "Frontend Developer", "Full Stack Developer", "DevOps Engineer", "Data Engineer", "QA Engineer", "IT Support", "Network Administrator", "Database Administrator", "Cloud Architect", "Solutions Architect", "Product Manager", "Technical Writer"] },
  { id: "finance", label: "Finance", fields: ["Accountant", "Financial Analyst", "CFO", "Auditor", "Tax Specialist", "Investment Banker", "Risk Manager", "Compliance Officer", "Financial Planner", "Payroll Specialist"] },
  { id: "hr", label: "Human Resources", fields: ["HR Manager", "Recruiter", "HR Specialist", "Training Coordinator", "Employee Relations", "Compensation & Benefits", "HR Generalist"] },
  { id: "marketing", label: "Marketing", fields: ["Marketing Manager", "Digital Marketing Specialist", "Content Writer", "SEO Specialist", "Social Media Manager", "Brand Manager", "Marketing Analyst", "Email Marketing Specialist", "Product Marketer"] },
  { id: "sales", label: "Sales", fields: ["Sales Manager", "Sales Representative", "Account Executive", "Business Development", "Sales Engineer", "Inside Sales", "Territory Manager"] },
  { id: "operations", label: "Operations", fields: ["Operations Manager", "Supply Chain Manager", "Logistics Manager", "Procurement Specialist", "Process Analyst", "Project Manager", "Operations Analyst"] },
  { id: "healthcare", label: "Healthcare", fields: ["Doctor", "Nurse", "Pharmacist", "Medical Assistant", "Healthcare Administrator", "Physical Therapist", "Dentist"] },
  { id: "education", label: "Education", fields: ["Teacher", "Professor", "Instructor", "Education Coordinator", "School Principal", "Curriculum Developer"] },
  { id: "manufacturing", label: "Manufacturing", fields: ["Production Manager", "Quality Assurance", "Maintenance Engineer", "Plant Manager", "Manufacturing Engineer", "Warehouse Manager"] },
  { id: "real_estate", label: "Real Estate", fields: ["Real Estate Agent", "Property Manager", "Real Estate Developer", "Land Surveyor", "Broker"] },
  { id: "hospitality", label: "Hospitality", fields: ["Hotel Manager", "Chef", "Restaurant Manager", "Event Coordinator", "Concierge", "Housekeeping Manager"] },
  { id: "retail", label: "Retail", fields: ["Store Manager", "Sales Associate", "Visual Merchandiser", "Inventory Manager", "Cashier"] },
  { id: "entertainment", label: "Entertainment", fields: ["Director", "Producer", "Actor", "Designer", "Cinematographer", "Editor"] },
  { id: "automotive", label: "Automotive", fields: ["Mechanic", "Service Manager", "Automotive Engineer", "Technician", "Sales"] },
  { id: "legal", label: "Legal", fields: ["Lawyer", "Paralegal", "Legal Assistant", "Compliance Officer", "Contract Manager"] },
  { id: "construction", label: "Construction", fields: ["Construction Manager", "Project Manager", "Architect", "Engineer", "Foreman", "Estimator"] },
  { id: "agriculture", label: "Agriculture", fields: ["Farm Manager", "Agronomist", "Agricultural Engineer", "Veterinarian"] },
  { id: "other", label: "Other", fields: [] }
];

// Salary ranges in PHP
export const SALARY_RANGES = [
  { min: 15000, max: 25000, label: "₱15,000 - ₱25,000" },
  { min: 25000, max: 40000, label: "₱25,000 - ₱40,000" },
  { min: 40000, max: 60000, label: "₱40,000 - ₱60,000" },
  { min: 60000, max: 100000, label: "₱60,000 - ₱100,000" },
  { min: 100000, max: 150000, label: "₱100,000 - ₱150,000" },
  { min: 150000, max: 250000, label: "₱150,000 - ₱250,000" },
  { min: 250000, max: 500000, label: "₱250,000 - ₱500,000" },
  { min: 500000, max: 1000000, label: "₱500,000+" }
];
